### ISSUE TITLE
System Integrity Protection blocks "bless" utility, use "systemsetup" instead

### ISSUE THREAD

**Issue by compenguy** [herrbischoff/awesome-macos-command-line#143]
In "Disks and Volumes", you document using "bless" to set boot volume.

With the newly-introduced [System Integrity Protection](https://developer.apple.com/library/content/documentation/Security/Conceptual/System_Integrity_Protection_Guide/ConfiguringSystemIntegrityProtection/ConfiguringSystemIntegrityProtection.html) (appears to have been introduced with El Capitan), you must either disable it (using csrutil) or use the "[systemsetup](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man8/systemsetup.8.html)" utility instead.

systemsetup -setstartupdisk "/path/to/mounted/volume"

**Comment by herrbischoff** [comment]
Thanks! I will look into this and amend the respective entry.

**Comment by vsipuli** [comment]
In macOS 10.13.2, it seems that not even `systemsetup` can any longer set the startup disk when System Integrity Protection is enabled:

```
$ sudo systemsetup -setstartupdisk "/Volumes/Macintosh HD/System/Library/CoreServices"
Setting startup disk not allowed while System Integrity Protection is enabled.
```

**Comment by herrbischoff** [comment]
The correct usage is:

```
$ sudo systemsetup -setstartupdisk /System/Library/CoreServices
Set Startup Disk to Path: /System/Library/CoreServices
```

Since SIP, `systemsetup` can only set the startup disk for SIP protected versions of macOS. According to the docs, if you try to use it on a SIP enabled installation with Boot Camp, macOS versions earlier than 10.11 or installations with SIP disabled, this command will fail. As I have disabled SIP on my machine, could you verify that it works for two SIP enabled installations?

**Comment by vsipuli** [comment]
Both of the macOS volumes have SIP enabled:

    $ csrutil status
    System Integrity Protection status: enabled.

But still setting the startup disk gives the following error:

    $ sudo systemsetup -setstartupdisk /System/Library/CoreServices
    Setting startup disk not allowed while System Integrity Protection is enabled.

So it seems that at least I cannot get it working even with SIP enabled.

**Comment by herrbischoff** [comment]
I really have to say that this System Integrity Protection mechanism appears to be mainly useful for the typical iOS-style user, not advanced desktop users. Since I ran into multiple issues already, I have completely and permanently disabled SIP. It also appears to survive the installation of system updates.

**Comment by herrbischoff** [comment]
As there appears to be no useful solution, I'm going to close this. I'm also going to disable Issues from now on as it increasingly attracts forum style discussion. This is not what they are for.
